---
abstract: 'A POE-based parser for DSV based files.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-DSV
no_index:
  directory:
    - inc
    - t
requires:
  Error::Pure: 0.11
  POE::Filter: 0
  Text::DSV: 0.05
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=POE-Filter-DSV
  homepage: https://github.com/tupinek/POE-Filter-DSV
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/POE-Filter-DSV
version: 0.01
